const channels=[{id:'paper',name:'Paper Moon',handle:'@papermoon',verified:true,description:'여백과 종이의 질감을 큐레이션하는 독립 매거진 채널입니다.',followers:'18.2만',products:['cereal','poster'],emoji:'🌙',cover:'linear-gradient(135deg,#f3eadb,#b8d8d3)'},{id:'haneul',name:'Studio Haneul',handle:'@studiohaneul',verified:true,description:'하늘과 구름에서 영감 받은 포스터와 엽서.',followers:'7.8만',products:['cloud'],emoji:'☁️',cover:'linear-gradient(135deg,#eaf4f8,#d7e4ff)'},{id:'tokyo',name:'Tokyo Letter',handle:'@tokyoletter',verified:true,description:'계절의 편지지를 현지 제작으로 전합니다.',followers:'4.1만',products:['letter'],emoji:'✉️',cover:'linear-gradient(135deg,#f7e8dd,#e7efe9)'},{id:'cloud',name:'Cloud Atelier',handle:'@cloudatelier',verified:true,description:'작은 오브제와 3D 아트워크.',followers:'2.9만',products:['neko','hinge'],emoji:'🪁',cover:'linear-gradient(135deg,#fff7dc,#d4eee8)'}];
const products=[{id:'cereal',name:'CEREAL Magazine Issue 26',channelId:'paper',price:28000,category:'잡지',localProduction:true,description:'공식 라이선스 파일을 기반으로 국내 인증 인쇄소에서 제작되는 프리미엄 매거진.',emoji:'📖',tags:['종이 감성','오늘 인기','공식 채널']},{id:'poster',name:'Cloud Archive Poster',channelId:'haneul',price:19000,category:'포스터',localProduction:true,description:'구름 아카이브를 한지 질감 용지에 출력한 미니멀 포스터.',emoji:'🖼️',tags:['한지 포스터','미니멀 오브제']},{id:'neko',name:'Lucky Neko 3D Figure',channelId:'cloud',price:42000,category:'3D',localProduction:true,description:'권리자가 등록한 3D 설계 파일로 가까운 제작소에서 출력하는 고양이 피규어.',emoji:'🐱',tags:['고양이 피규어','3D','오늘 인기']},{id:'hinge',name:'Brass Hinge',channelId:'cloud',price:11500,category:'부품',localProduction:true,description:'해외 부품 도면을 인증 파트너가 소량 가공합니다.',emoji:'⚙️',tags:['부품']},{id:'letter',name:'Autumn Letter Set',channelId:'tokyo',price:14500,category:'한정판',localProduction:true,description:'가을 한정 편지지 세트를 국내 제작으로 빠르게 받아보세요.',emoji:'🍂',tags:['종이 감성','공식 채널']}];
let state={screen:'home',selectedChannel:'paper',selectedProduct:'cereal',subscribed:new Set(['paper','haneul','tokyo','cloud']),query:'',paid:false,step:3,file:'',created:''};
const partner='서울 인쇄소 2741 ✓', root=document.getElementById('root'), won=n=>n.toLocaleString('ko-KR')+'원', ch=id=>channels.find(c=>c.id===id), pr=id=>products.find(p=>p.id===id);
function set(p){Object.assign(state,p);render()} function goProduct(id){set({selectedProduct:id,selectedChannel:pr(id).channelId,screen:'product'})} function goChannel(id){set({selectedChannel:id,screen:'channel'})}
function shell(content){root.innerHTML=`<div class="page"><main class="phone"><header class="top"><button class="brand" data-go="home">도화지 <span>DOHWAJI</span></button><div><button class="icon">⌕</button><button class="icon">◦</button></div></header>${content}<nav>${[['home','⌂','홈'],['explore','◇','탐색'],['subs','♡','구독'],['orders','▤','주문'],['me','☻','내정보']].map(([id,ic,la])=>`<button class="${state.screen===id?'on':''}" data-go="${id}"><b>${ic}</b><span>${la}</span></button>`).join('')}</nav></main></div>`; bind()}
function productGrid(items){return `<div class="grid">${items.map(p=>`<article class="product" data-product="${p.id}"><div class="pic">${p.emoji}</div><b>${p.name}</b><p>${won(p.price)}</p><span>국내 생산</span><button>♡</button></article>`).join('')}</div>`}
function renderHome(){shell(`<section><div class="hero"><p>물건 대신</p><p>아이디어를</p><p>이동시키다</p><small>공식 권리자의 아이디어가 가까운 제작소에서 제품이 됩니다.</small></div><div class="chips">${['전체','잡지','포스터','3D','부품','한정판'].map(x=>`<button>${x}</button>`).join('')}</div><h2>공식 채널</h2>${channels.slice(0,3).map(c=>`<article class="channelCard" data-channel="${c.id}"><div class="avatar">${c.emoji}</div><div><b>${c.name} ✓</b><p>${c.description}</p></div><div class="mini">${c.products.slice(0,2).map(id=>`<span>${pr(id).emoji}</span>`).join('')}</div></article>`).join('')}<h2>인기 상품</h2>${productGrid(products.slice(0,4))}</section>`)}
function renderExplore(){const q=state.query.toLowerCase(); const items=products.filter(p=>([p.name,p.category,p.description,...p.tags,ch(p.channelId).name].join(' ').toLowerCase().includes(q))); shell(`<section><input class="search" id="search" placeholder="채널, 제품, 작가 검색" value="${state.query}"><div class="chips filters">${['공식 채널','한국 현지 생산','3D','부품','오늘 인기'].map(x=>`<button data-query="${x}">${x}</button>`).join('')}</div><h2>트렌드 태그</h2><div class="tags">${['종이 감성','미니멀 오브제','한지 포스터','고양이 피규어'].map(x=>`<button data-query="${x}">#${x}</button>`).join('')}</div>${productGrid(items)}</section>`); document.getElementById('search').oninput=e=>set({query:e.target.value})}
function renderChannel(){const c=ch(state.selectedChannel); shell(`<section><div class="cover" style="background:${c.cover}"></div><div class="profile"><div class="avatar big">${c.emoji}</div><h1>${c.name} ✓</h1><p>${c.description}</p><div class="stats"><b>팔로워 ${c.followers}</b><b>상품 ${c.products.length}</b></div><button class="primary" id="subBtn">${state.subscribed.has(c.id)?'구독중 ✓':'구독'}</button></div><div class="tabs"><b>상품</b><span>소개</span><span>후기</span></div>${productGrid(products.filter(p=>p.channelId===c.id))}</section>`); document.getElementById('subBtn').onclick=()=>{state.subscribed.has(c.id)?state.subscribed.delete(c.id):state.subscribed.add(c.id);render()}}
function renderProduct(){const p=pr(state.selectedProduct), c=ch(p.channelId); shell(`<section><div class="productHero">${p.emoji}</div><p class="dots">● ○ ○</p><button class="link" data-channel="${c.id}">${c.name} ✓</button><h1>${p.name}</h1><h2>${won(p.price)}</h2><span class="badge">한국 현지 생산</span><p>${p.description}</p><div class="info"><b>해외 배송 대신 국내 제작</b><ul><li>공식 라이선스</li><li>한국 현지 생산</li><li>빠른 배송 · 2026년 7월 13일 예정</li></ul></div><select><option>기본 옵션</option><option>프리미엄 종이</option></select><div class="actions"><button>장바구니</button><button class="primary" data-go="checkout">구매하기</button></div></section>`)}
function cost(price){const rows=[['상품 가격',price],['권리자 로열티',3200],['국내 제작',6500],['국내 배송',3000],['도화지 수수료',1800]], total=rows.reduce((a,r)=>a+r[1],0);return `<div class="card">${rows.map(r=>`<p class="row"><span>${r[0]}</span><b>${won(r[1])}</b></p>`).join('')}<hr><p class="row total"><span>총 결제 금액</span><b>${won(total)}</b></p></div>`}
function renderCheckout(){const p=pr(state.selectedProduct); shell(`<section><h1>주문/결제</h1>${state.paid?'<div class="toast">결제 완료! 제작 추적으로 이동합니다.</div>':''}<div class="card"><b>배송지</b><p>서울특별시 성동구 도화지로 12</p></div><div class="channelCard"><div class="avatar">${p.emoji}</div><div><b>${p.name}</b><p>${won(p.price)}</p></div></div><div class="card"><b>제작 파트너</b><p>${partner}</p></div>${cost(p.price)}<button class="primary full" id="pay">결제하기</button></section>`); document.getElementById('pay').onclick=()=>{state.paid=true;render();setTimeout(()=>set({screen:'tracking'}),700)}}
function renderTracking(){const p=pr(state.selectedProduct), steps=['주문 완료','라이선스 확인','파일 전송','국내 제작','검수','배송 중','배송 완료']; shell(`<section><h1>제작 추적</h1><p>본 상품은 공식 라이선스를 보유한 국내 파트너사에서 제작되고 있습니다.</p><div class="card"><p>주문번호 DHW-20260709-026</p><p>예상 도착일 2026년 7월 13일</p><p>제작 파트너 ${partner}</p><p>상품 ${p.name}</p></div><div class="timeline">${steps.map((s,i)=>`<div class="${i<=state.step?'done':''}">✓ <span>${s}</span></div>`).join('')}</div><button class="primary full" id="next">다음 단계 시뮬레이션</button></section>`); document.getElementById('next').onclick=()=>set({step:Math.min(state.step+1,6)})}
function renderSubs(){shell(`<section><h1>구독</h1><div class="chips">${channels.filter(c=>state.subscribed.has(c.id)).map(c=>`<button data-channel="${c.id}">${c.name}</button>`).join('')}</div>${products.map(p=>`<article class="feed"><b>${ch(p.channelId).name} ✓</b><small> · 2시간 전</small><div class="feedImg">${p.emoji}</div><p><b>New Arrival</b><br>${p.name}을 도화지 국내 제작으로 만나보세요.</p><button>저장</button><button data-product="${p.id}">바로 보기</button></article>`).join('')}</section>`)}
function renderMe(){shell(`<section><h1>내정보</h1><button class="primary full" data-go="create">＋ 공식 채널 만들기</button><div class="card"><b>도화지 멤버</b><p>구독 채널 ${state.subscribed.size}개 · 주문 1건</p></div></section>`)}
function renderCreate(){shell(`<section><h1>공식 채널 만들기</h1><input id="created" placeholder="채널 이름"><input placeholder="프로필 이미지 URL 또는 설명"><label class="upload">↥ 보안 파일 업로드<input id="file" type="file"></label><p id="fileName"></p><select><option>인쇄</option><option>3D</option><option>부품</option></select><input placeholder="가격 설정"><input placeholder="판매 가능 지역" value="한국"><button class="primary full" id="createBtn">채널 생성</button><div id="createdMsg"></div></section>`); document.getElementById('file').onchange=e=>document.getElementById('fileName').textContent='선택된 파일: '+(e.target.files[0]?.name||''); document.getElementById('createBtn').onclick=()=>document.getElementById('createdMsg').innerHTML='<div class="toast">가상 채널 페이지가 생성되었습니다.</div>'}
function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>set({screen:el.dataset.go}));document.querySelectorAll('[data-product]').forEach(el=>el.onclick=()=>goProduct(el.dataset.product));document.querySelectorAll('[data-channel]').forEach(el=>el.onclick=()=>goChannel(el.dataset.channel));document.querySelectorAll('[data-query]').forEach(el=>el.onclick=()=>set({query:el.dataset.query,screen:'explore'}))}
function render(){({home:renderHome,explore:renderExplore,channel:renderChannel,product:renderProduct,checkout:renderCheckout,tracking:renderTracking,orders:renderTracking,subs:renderSubs,me:renderMe,create:renderCreate}[state.screen])()} render();
